### PR TITLE
Only disable Netrw for local files

### PR DESCRIPTION
**Pull request by infokiller**

### CODE REVIEW

**Comment by infokiller** [comment]
Friendly ping @rafaqz

**Comment by rafaqz** [comment]
Some reasons for why this is needed would help me decide to hit merge. What is your problem with the current behaviour?

**Comment by infokiller** [comment]
The comment in the source describes it: when you use vim for remote files, you want to keep using netrw, and not use ranger. Without this PR, you disable netrw for all files, not just local ones.

**Comment by rafaqz** [comment]
You may want to, but do people generally always want to use netrw and not ranger? does ranger not work for that? could it?

It's not something I do. Please explain a little more. Once I merge your PR I own any problems with it...

**Comment by infokiller** [comment]
You can't use ranger for remote files. So this plugin breaks editing remote files in vim.

**Comment by infokiller** [comment]
Thanks for merging!

**Pull request merged**
